server:
  port: 80
urlPath: "{download: '/download/**', upload: '/upload/**', get: '/get/**', getSingle: '/get'}"
url:
  path:
    directory: /file/get/
    file: /file/download/

security:
  oauth2:
    resource.filter-order: 3
  encoding-strength: 256
  jwt:
    client-id: testjwtclientid
    resource-ids: testjwtresourceid
spring:
  datasource:
    url: jdbc:h2:mem:test2
    username: sa
    password:
    driverClassName: org.h2.Driver
    schema: classpath:/sql-scripts/schema.sql
    data: classpath:/sql-scripts/data.sql
  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: validate
      show-sql: true
    properties:
      hibernate:
        enable_lazy_load_no_trans: true