server:
  port: 443
  ssl:
    key-store-type: PKCS12
    key-store: classpath:keystore.p12
    key-store-password: password
    key-alias: tomcat
urlPath: "{download: '/download/**', upload: '/upload/**', get: '/get/**', getSingle: '/get'}"
url:
  path:
    directory: /file/get/
    file: /file/download/

security:
  oauth2:
    resource.filter-order: 3
  encoding-strength: 256
  jwt:
    client-id: testjwtclientid
    resource-ids: testjwtresourceid
  require-ssl: true
spring:
  datasource:
    url: jdbc:mysql://${jdbc_url}:3306/db
    username: ${jdbc_login}
    password: ${jdbc_password}
    driverClassName: com.mysql.jdbc.Driver
  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: validate
      show-sql: true
    properties:
      hibernate:
        enable_lazy_load_no_trans: true